name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.arundevopsengineer }}
          password: ${{ dckr_pat_nJcqqmpC40yz2wREDy6wwAYuYbs }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.arundevopsengineer }}/aws-devops-learning:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/aws-devops-learning:latest
